app:
  title: Scaffolded Backstage App
  baseUrl: http://localhost:3000

organization:
  name: Talentica Software

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    connect-src:
      - "'self'"
      - "http:"
      - "https:"
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  server:
    port: 7008

database:
  client: pg
  connection:
    host: '127.0.0.1'
    port: '5432'
    user: 'postgres'
    password: 'useradmin'

integrations:
  github:
    - host: github.com
      token: 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

proxy:
  endpoints:
    '/WeatherForecast':
      target: 'http://localhost:7008/api/weather'
      changeOrigin: true   

techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'docker' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'.

auth:
  environment: development
  providers:
    guest: {}
    github:
      development:
        clientId: Ov23liOWIYzez36krjCn
        clientSecret: 1deb6be944f18aa350598c7e5907d14bf9082ac2
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName

scaffolder:
  # See https://backstage.io/docs/features/software-templates/configuration for software template options

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow:
        - Component
        - System
        - API
        - Resource
        - Location
        - Template
  providers:
    github:
      # Define a unique provider ID
      myProvider:
        # Replace with your individual account name
        organization: 'ArpitPandeyTalentica'
        # Search for all YAML files in the repository
        catalogPath: '/api/*.yaml'
        filters:
          branch: 'main' # Ensure this matches your branch name
          repository: 'BackstageAPISample' # Include the specific repository name
        schedule:
          frequency: { minutes: 30 }
          timeout: { minutes: 5 }

  locations:
    - type: file
      target: ../../examples/entities.yaml
    - type: file
      target: ../../examples/template/template.yaml
      rules:
        - allow:
            - Template
    - type: file
      target: ../../examples/org.yaml
      rules:
        - allow:
            - User
            - Group

permission:
  enabled: true
